### ISSUE TITLE
Can I be added?

### ISSUE THREAD

**Issue by pmaxhogan** [CodeReviewCommunity/CodeReviewCommunity.github.io#10]

**Comment by latk** [comment]
You are [this programmer5000](https://codereview.stackexchange.com/users/131146/programmer5000), right?

I see that you only have 101 reputation on the site, without any questions or answers. Additionally, the CodeReviewCommunity on GitHub doesn't really fulfill a purpose for the time being. I suggest that you become a more active member on Code Review, and feel free to discuss the Github community in [The 2nd Monitor](https://chat.stackexchange.com/rooms/info/8595/the-2nd-monitor) (our chat room).
