### ISSUE TITLE
Let people join!

### ISSUE THREAD

**Issue by acostarelli** [CodeReviewCommunity/CodeReviewCommunity.github.io#5]
I was reading over [this Issue on this repo](https://github.com/CodeReviewCommunity/CodeReviewCommunity.github.io/issues/4). It seems to me that this user was rejected _because the group was no longer active._

That doesn't make much sense to me: how is this group ever going to become active if you don't let people join? Rather than rejecting people who want to join, you should allow them in. These new people will spark new projects, which will get more people to join, which will spark more projects... you get the point.

As this group grows, the Code Review community will grow too. With a central point to put projects for other CRitters to willingly help on, users will become more integrated with each other, which will boost the community in many ways.

As of right now, the only two major projects going on in Code Review are Rubberduck and Cardshifter. By opening up this group for more people to come, the number of projects would greatly increase.

Of course, however, if you were to go along with this idea, you may want to set down some ground rules. For example, you don't want people creating hundreds of repositories that should really belong on their personal GitHub.

As an extra, you could "appoint moderators" of this group to make sure that people are following these rules.

**Comment by acostarelli** [comment]
Oh, and while I'm at it,

I'm SirPython and I'd like to join the assembly team.

:)

**Comment by rolfl** [comment]
Done
