### ISSUE TITLE
Can I be added?

### ISSUE THREAD

**Issue by ghost** [CodeReviewCommunity/CodeReviewCommunity.github.io#9]
Thanks!

**Comment by Zomis** [comment]
What is your Code Review user profile?

**Comment by ghost** [comment]
http://codereview.stackexchange.com/users/15466

Sorry for the delayed response, hectic week. :)

**Comment by Zomis** [comment]
I see that you only have 101 reputation on the site, with one deleted question and no further posts beyond that. Additionally, the CodeReviewCommunity on github doesn't really fulfill a purpose for the time being. I suggest that you become a more active member on Code Review, and feel free to discuss the Github community in [The 2nd Monitor](http://chat.stackexchange.com/rooms/8595/the-2nd-monitor)

**Comment by ghost** [comment]
Thanks, will do!
